name: Publish Check

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  schedule:
    - cron: '* * * * *' # Every minute

jobs:
  testnet-autodeploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Check and Publish
        uses: ./ # Uses an action in the root of the repository
        with:
          package_dir: example/aptos-testnet-autodeploy
          check_address: "0x7fd244ebf577f646130c97de424c480ce761729130d5fb433b7dd312574eaddc"
          named_addresses: module_addr=0x7fd244ebf577f646130c97de424c480ce761729130d5fb433b7dd312574eaddc
          private_key: ${{ secrets.PRIVATE_KEY }}
          upgrade_allowed: true
